In [ ]:
# 모듈 호출
import numpy as np

In [5]:
a = np.array(1)
a

array(1)

In [12]:
# 배열 생성 및 타입 확인

array_1 = np.array([1,2,3])
print(array_1)
print(array_1.dtype)

array_2 = np.array([1,2.0,3])
print(array_2)
print(array_2.dtype)

array_3 = np.array([1,2.0,'3'])
print(array_3)
print(array_3.dtype)

[1 2 3]
int32
[1. 2. 3.]
float64
['1' '2.0' '3']
<U32


In [21]:
# 자료형 지정

dtype1 = np.array([1,2,3], dtype=np.int8)
print(dtype1.dtype)

dtype2 = np.array([1,2,3,4], dtype=np.float)
print(dtype2.dtype)

dtype3 = np.array([1,2,3,4,5], dtype=np.str)
print(dtype3.dtype)

int8
float64
<U1


C:\Users\Admin\AppData\Local\Temp\ipykernel_16768\720618511.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype2 = np.array([1,2,3,4], dtype=np.float)
C:\Users\Admin\AppData\Local\Temp\ipykernel_16768\720618511.py:7: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype3 = np.array([1,2,3,4,5], dtype=np.str)


In [25]:
# 배열 정보 확인

print(array_1.shape)  # 배열 크기
print(array_1.ndim)   # 배열 차원

(3,)
1


In [28]:
# 배열 생성

# 1 차원
vector = np.array([1,2,3])  

print(vector)
print(vector.shape)
print(vector.ndim)
print(vector.dtype)

[1 2 3]
(3,)
1
int32


In [30]:
# 2 차원
matrix = np.array([[1,2,3], [4,5,6]])

print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


In [31]:
# 3 차원
tensor = np.array([[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]])

print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
(1, 4, 3)
3
int32


In [33]:
# 배열 요소 개수 확인
print(vector.size)
print(matrix.size)
print(tensor.size)

3
6
12


In [40]:
# 2 차원 리스트 변환
list3 = [[1,2,3], [4,5,6]]
arr3 = np.array(list3)
print(arr3)

# shape 다른 리스트인 경우
list4 = [[1,2,3], [4,5,6,7]]
arr4 = np.array(list4)
print(arr4)

[[1 2 3]
 [4 5 6]]
[list([1, 2, 3]) list([4, 5, 6, 7])]


C:\Users\Admin\AppData\Local\Temp\ipykernel_16768\2773617494.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array(list4)


In [42]:
# 자료형 변환(튜플)
tuple1 = (1,2,3)
arr = np.array(tuple1)
print(arr)

arr2 = np.array([1,2,3])
tuple2 = tuple(arr2)
print(tuple2)

[1 2 3]
(1, 2, 3)


In [46]:
# 자료형 변환(세트, 딕셔너리)
set1 = {1,2,3}
arr = np.array(set1)
print(arr)
print(arr.size)

dict1 = {'a':1,'b':2,'c':3}
arr = np.array(dict1)
print(arr)
print(arr.size)

{1, 2, 3}
1
{'a': 1, 'b': 2, 'c': 3}
1


In [57]:
# 배열 인덱싱
list_1 = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(list_1[0][0][0])

arr_1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_1[0][0][0])
print(arr_1[0,0,0])

1
1
1


In [72]:
arr = np.array([1,2,3,4,5])
print(arr[[True,False,True,True,False]])

# 조건
print(arr[arr>=3])

[1 3 4]
[3 4 5]


In [77]:
# 배열 슬라이싱
matrix = np.array([[1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,15],
                   [16,17,18,19,20]])

print(matrix[:,0])
print(matrix[:,:1]) # 2 차원 유지

[ 1  6 11 16]
[[ 1]
 [ 6]
 [11]
 [16]]


In [82]:
# 1 행 전체 슬라이싱
print(matrix[1,:])
print(matrix[1])  # rank > row > col 순으로 : (콜론) 생략 가능

print(matrix[1:2,:]) # 2차원 유지
print(matrix[[1]])   # or

[ 6  7  8  9 10]
[ 6  7  8  9 10]
[[ 6  7  8  9 10]]
[[ 6  7  8  9 10]]


In [85]:
# 3~4 열 전체 슬라이싱
print(matrix[:,3:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]
[2 3 4]
[[13 14 15]
 [18 19 20]]


In [ ]:
# 0행, 1~3열 슬라이싱
print(matrix[0,1:-1])

In [ ]:
# 2~3행, 2~4열 슬라이싱
print(matrix[-2:,-3:])

In [90]:
# 1~2행, 1~2열 슬라이싱
print(matrix[1:-1,1:3])

[[ 7  8]
 [12 13]]


In [92]:
# 1,3 행, 2~4 열 슬라이싱
print(matrix[[1,3],2:])

[[ 8  9 10]
 [18 19 20]]


In [93]:
# 1~2 행, 1,3 열 슬라이싱
print(matrix[1:-1,[1,3]])

[[ 7  9]
 [12 14]]
