In [28]:
import numpy as np

In [4]:
# 파일 저장(tofile)
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')

[[-1.85741974  0.97772337  0.9753463  -0.98924606  1.57377201]
 [-0.37694937  0.70774623 -0.55827717  0.74335672  0.82246823]
 [ 0.18879525 -0.30782929 -0.30737293  0.53958402  0.75156296]]


In [5]:
# 파일 불러오기(fromfile)
m = np.fromfile('n.npy')
print(m)

[-1.85741974  0.97772337  0.9753463  -0.98924606  1.57377201 -0.37694937
  0.70774623 -0.55827717  0.74335672  0.82246823  0.18879525 -0.30782929
 -0.30737293  0.53958402  0.75156296]


In [8]:
# 파일 저장, 불러오기   주로 사용
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[-1.85741974  0.97772337  0.9753463  -0.98924606  1.57377201]
 [-0.37694937  0.70774623 -0.55827717  0.74335672  0.82246823]
 [ 0.18879525 -0.30782929 -0.30737293  0.53958402  0.75156296]]


In [10]:
# txt 파일 저장 / 불러오기
np.savetxt('n.txt',n)
np.loadtxt('n.txt')

array([[-1.85741974,  0.97772337,  0.9753463 , -0.98924606,  1.57377201],
       [-0.37694937,  0.70774623, -0.55827717,  0.74335672,  0.82246823],
       [ 0.18879525, -0.30782929, -0.30737293,  0.53958402,  0.75156296]])

In [11]:
# csv 파일 저장 / 불러오기
np.savetxt('n.csv',n)
np.loadtxt('n.csv')

array([[-1.85741974,  0.97772337,  0.9753463 , -0.98924606,  1.57377201],
       [-0.37694937,  0.70774623, -0.55827717,  0.74335672,  0.82246823],
       [ 0.18879525, -0.30782929, -0.30737293,  0.53958402,  0.75156296]])

In [43]:
np.unique

<function numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)>

In [57]:
# 파일 읽어오기
data = np.loadtxt('ex1_지역별전기요금.csv', delimiter=',',dtype=np.int32, encoding='euc-kr') 
print(data[:5,:])                                        #  'euc-kr', 'cp949'  encoding 해줄것

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


In [61]:
# 데이터 모양 확인
print(data.shape)
# 중복 지역 확인
print(np.unique(data[:,0]))

(17, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [63]:
# 데이터 확인  크기 순 정렬
print(data[:,1].argsort())

print(data[data[:,1].argsort()])

[ 9 14 10  4  6  0 16 13  5 12 11 15  7  3  2  8  1]
[[     10   49394     580   57091]
 [     15  258605     221   22180]
 [     11  323151     353   35470]
 [      5  380425     391   38020]
 [      7  425659     344   32331]
 [      1  565082     273   27177]
 [     17  584500     268   26899]
 [     14  634696     285   28556]
 [      6  668623     364   35245]
 [     13  726699     249   25120]
 [     12  734723     398   40049]
 [     16  742285     282   27901]
 [      8  947300     366   36274]
 [      4 1131034     230   22436]
 [      3 1144913     289   29043]
 [      9 2737725     361   36569]
 [      2 2827233     444   45111]]


In [65]:
# 전국 대상 가구수 합
print(np.sum(data[:,1]))

# 가구당 평균 정력 사용량의 전국 평균값
print(round(data[:,2].mean(),2))

14882047
335.18


In [69]:
# 가구당 평균 전력 사용량이 평균 이상인 지역과 대상 가구수 추출
avg = data[:,2].mean() # 가구당 평균 전력 사용량의 전국 평균
print(data[data[:,2]>avg,0:2])

[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]
