In [2]:
import numpy as np

In [5]:
# Reshape
arr = np.array([[1,2,3],
                [4,5,6]]) # 2*3 형태의 2차원 배열
print(arr.reshape(3,2))   # 3*2 형태의 배열로 변형

print(arr.reshape(3,1,2)) # 3*1*2 형태로 변형

[[1 2]
 [3 4]
 [5 6]]
[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [6]:
# Flatten
print(arr.flatten()) # 다차원을 1 차원으로

[1 2 3 4 5 6]


In [9]:
# Arange
print(np.arange(20))
print(np.arange(0,10,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 2 4 6 8]


In [10]:
# Arange + Reshape
print(np.arange(1, 26).reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [13]:
# Zeros  0으로 채워진 배열 생성
print(np.zeros(shape=(5,),dtype=np.int8))
print(np.zeros((5),int))
print(np.zeros((2,3)))

[0 0 0 0 0]
[0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Ones  1로 채워진 배열 생성
print(np.ones(shape=(5,),dtype=np.int8))
print(np.ones((5),int))
print(np.ones((2,3)))

[1 1 1 1 1]
[1 1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# Empty  비어있는 배열 생성
print(np.empty(shape=(10,),dtype=np.int32))
print(np.empty((2,5),np.int8))

[4128860 6029375 3801155 5570652 6619251 7536754 4259840 7143524 7209065
       0]
[[  64   -1 -113  -91   73]
 [   2    0    0    0    0]]


In [22]:
# zeros_like, ones_like, empty_like
# 입력 받은 배열과 같은 shape, dtype의 배열 생성
matrix = np.arange(20).reshape(4,5)
np.empty_like(matrix)

array([[-1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [25]:
# Identity 대각선 값1  나머지 0  정사각형
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
# eye  대각선이 1로 채워지는 행렬
# k : 입력 받은 수 만큼 오른쪽으로 이동
# M : 열의 개수 지정
print(np.eye(5))
print(np.eye(5,k=2,M=10))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [36]:
# Full  입력 값으로 채ㅐ워지는 행열
print(np.full((2,5),3))
print(np.full((5,4),'a'))

[[3 3 3 3 3]
 [3 3 3 3 3]]
[['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']]


In [39]:
# random.randint  범위 안의 랜덤 값 뽑기
print(np.random.randint(6))
print(np.random.randint(1,11))

5
7


In [43]:
# random.rand  0 ~ 1 값
np.random.rand(3,2)

array([[0.82984326, 0.66962588],
       [0.84582472, 0.24228387],
       [0.02151958, 0.01162181]])

In [44]:
# random.randn 평균 0, 표준편차 1
np.random.randn(3,2)

array([[ 0.37481766, -0.78676395],
       [ 1.70568021, -1.05660117],
       [-1.00158506, -0.17632602]])

In [47]:
# sum
matrix = np.arange(1,7).reshape(2,3)
print(matrix.sum())

print(matrix.sum(axis=0)) # 행끼리 더하기(위 아래)
print(matrix.sum(axis=1)) # 열끼리 더하기(좌 우)

21
[5 7 9]


In [50]:
# sum 3차원 배열 합
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor)
print(tensor.sum())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
171


In [54]:
# sum 3차원 배열 합
print(tensor.sum(axis=0))
print(tensor.sum(axis=1))
print(tensor.sum(axis=2))

[[21 24 27]
 [30 33 36]]
[[ 5  7  9]
 [17 19 21]
 [29 31 33]]
[[ 6 15]
 [24 33]
 [42 51]]


In [57]:
# 평균 mean
print(matrix.mean())       # 전체 평균
print(matrix.mean(axis=0)) # 행끼리 평균(위 아래)
print(matrix.mean(axis=1)) # 열끼리 평균(좌 우)

3.5
[2.5 3.5 4.5]
[2. 5.]


In [59]:
# 표준 편자(std)
print(matrix.std())        # 전체 표준 편차
print(matrix.std(axis=0))  # 행끼리 표준 편자(위 아래)
print(matrix.std(axis=1))  # 열끼리 표준 편자(좌 우)

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [60]:
# 지수(exp)
print(np.exp(matrix))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [61]:
# 로그(log)
print(np.log(matrix))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [62]:
# 제곱근(sqrt)
print(np.sqrt(matrix))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [63]:
# 삼각함수(sin)
print(np.sin(matrix))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [64]:
# 삼각함수(cos)
np.cos(matrix)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [65]:
# 삼각함수(tan)
np.tan(matrix)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [81]:
# 배열 정렬(sort)
# 1차원 배열 정렬
vector = np.array([np.random.randint(1,100)for n in range(5)])
print(vector)
print(np.sort(vector))       # 오름차순
print(np.sort(vector)[::-1]) # 내립차순

[41 14 83 30 16]
[14 16 30 41 83]
[83 41 30 16 14]


In [83]:
# 2차원 배열 정렬
print(np.sort(matrix))  # 열 기준 정렬
print(np.sort(matrix, axis=0))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [84]:
# 배열 합치기(vstack)
# 2개 이상의 배열 수직 합체
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

np.vstack([vector1,vector2])

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
# 배열 합치기(hstack)
# 2개 이상의 배열 수평 합체
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

np.hstack([vector1,vector2])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [92]:
# 배열 합치기(concatenate)
# 2개 이상의 배열 수직, 수평 합체
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

np.concatenate([vector1,vector2],axis=0)

[1 2 3 4 5 6]


In [94]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

np.concatenate([vector1,vector2],axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [97]:
# 행/열 바꾸기(transpose)
matrix3 = np.array([[5,6]])
print(matrix3)

print(matrix3.transpose())  # 두개 사용 가능
print(matrix3.T)

[[5 6]]
[[5]
 [6]]
[[5]
 [6]]


In [101]:
# transpose + concatenate
print(np.concatenate([matrix3,matrix3]))
print(np.concatenate([matrix3,matrix3],axis=1))

[[5 6]
 [5 6]]
[[5 6 5 6]]


In [110]:
# 인덱스 반환 함수
# 최대값, 최소값
a = np.arange(1,11).reshape(2,5)
print(a)
print(np.argmax(a),np.argmin(a))
print(np.argmax(a,axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
9 0
[1 1 1 1 1]


In [113]:
b = np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2]])
print(b)
print(np.argmax(b,axis=1))
print(np.argmax(b,axis=0))

[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]]
[3 2 1]
[2 2 1 0]
