In [3]:
import numpy as np

In [4]:
# 리스트의 덧셈
list1 = [1,2,3]
list2 = [4,5,6]
list1 + list2

[1, 2, 3, 4, 5, 6]

In [16]:
# 배열의 산칙연산
# 배열 모양이 같은 경우
arr1 = np.array([1,2,3,4]).reshape(2,2)
arr2 = np.array([4,5,6,4]).reshape(2,2)
print(arr1+arr2)
print(np.add(arr1,arr2))

print(" ")
print(arr1-arr2)
print(np.subtract(arr1,arr2))

print(" ")
print(arr1*arr2)
print(np.multiply(arr1,arr2))

print(" ")
print(arr1/arr2)
print(np.divide(arr1,arr2))

print(" ")
print(arr1%arr2)

print(" ")
print(arr1//arr2)

[[5 7]
 [9 8]]
[[5 7]
 [9 8]]
 
[[-3 -3]
 [-3  0]]
[[-3 -3]
 [-3  0]]
 
[[ 4 10]
 [18 16]]
[[ 4 10]
 [18 16]]
 
[[0.25 0.4 ]
 [0.5  1.  ]]
[[0.25 0.4 ]
 [0.5  1.  ]]
 
[[1 2]
 [3 0]]
 
[[0 0]
 [0 1]]


In [20]:
# 배열 모양이 다른 경우
a = 10  # 지정
vector = np.array([1,2,3])
print(a+vector)

vector2 = np.array([[1,2,3],[4,5,6]])
print(a+vector2)

[11 12 13]
[[11 12 13]
 [14 15 16]]


In [22]:
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(1,3)
print(matrix)
print(vector)

matrix+vector

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]]


array([[12, 14, 16],
       [15, 17, 19],
       [18, 20, 22]])

In [36]:
arr1 = np.array([1,2,3])
print(arr1)

arr2 = np.array([1,2,3]).reshape(3,1)
print(arr2)

arr1+arr2

[1 2 3]
[[1]
 [2]
 [3]]


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [37]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).T
np.dot(arr1,arr2)

14

In [40]:
arr3 = np.arange(1,7).reshape(2,3)
arr4 = np.arange(11,17).reshape(3,2)
np.dot(arr3,arr4)

array([[ 82,  88],
       [199, 214]])